#!/bin/bash

echo "Packing paper ..."
cp llncs.cls ../pnse14-lmk/.
cp lmk_pnse.bbl ../pnse14-lmk/.
cp macros.tex ../pnse14-lmk/.
cp lmk_pnse.tex ../pnse14-lmk/pnse14-lmk.tex
cp pnse_lmk_copyright_signed.pdf ../pnse14-lmk/.

cd ..

zip -r pnse14-lmk.zip pnse14-lmk
echo "Done"